import 'dart:convert';
import 'package:myactivity_project/models/Approval%20Return/model_approval_return.dart';
import 'package:myactivity_project/models/Competitor%20Checking/model_tabel_approve.dart';
import 'package:myactivity_project/service/SP_service/SP_service.dart';
import 'package:http/http.dart' as http; 
import 'package:myactivity_project/tools/settingsralstools.dart';
import 'package:shared_preferences/shared_preferences.dart';
part 'ApprovalReturn_service.dart';
part 'CompetitorChecking_Approve.dart';
part 'Myactivity_Input.dart';
part 'Myactivity_edit.dart';
part 'Login_service.dart';
part 'Url.dart'; 
