import 'package:cool_alert/cool_alert.dart';
import 'package:expandable_bottom_bar/expandable_bottom_bar.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_barcode_scanner/flutter_barcode_scanner.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_iconly/flutter_iconly.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:form_field_validator/form_field_validator.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:myactivity_project/widget/import.dart';
import 'package:responsive_framework/responsive_wrapper.dart';
import 'package:screen_brightness/screen_brightness.dart';
import 'dart:math' as math;
import 'package:stepper_list_view/stepper_list_view.dart';
import 'package:myactivity_project/base/base_params.dart';
import '../../cubit/surat_jalan/surat_jalan_cubit.dart';
import '../../data/model/scan_sj_body.dart';
import '../../utils/keyboard_utils.dart';
import '../../utils/logging.dart';
import '../../utils/popup_widget.dart';
import 'package:myactivity_project/base/base_colors.dart' as baseColor;
import 'package:myactivity_project/base/base_params.dart' as baseParam;
part 'ramayana_suratjalan_lacak.dart';
part 'ramayana_suratjalan_scan.dart';
part 'ramayana_suratjalan_submenu.dart';
