import 'dart:collection';
import 'dart:convert';
import 'dart:math';
import 'package:device_info_plus/device_info_plus.dart';
import 'package:expandable_bottom_bar/expandable_bottom_bar.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_iconly/flutter_iconly.dart';
import 'package:flutter_udid/flutter_udid.dart';
import 'package:http/http.dart' as http;
import 'package:dio/dio.dart';
import 'package:myactivity_project/models/Competitor%20Checking/model_tabel_approve.dart';
import 'package:myactivity_project/models/Hak%20Akses/model_hakakses.dart';
import 'package:myactivity_project/widget/import.dart';
import 'package:myactivity_project/service/API_service/API_service.dart';
import 'package:myactivity_project/service/SP_service/SP_service.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:intl/intl.dart';
import 'package:myactivity_project/tools/settingsralstools.dart';

part 'ramayana_comcek_approve.dart';
part 'ramayana_comcek_history.dart';
part 'ramayana_comcek_submenu.dart';