import 'dart:async';
import 'dart:convert';
// import 'package:barcode_flutter/barcode_flutter.dart';
import 'package:device_info_plus/device_info_plus.dart';
import 'package:dio/dio.dart';
import 'package:expandable_bottom_bar/expandable_bottom_bar.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:flutter_udid/flutter_udid.dart';
import 'package:flutter_windowmanager/flutter_windowmanager.dart';
import 'package:form_field_validator/form_field_validator.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:http/http.dart' as http;
import 'package:flutter/services.dart';
import 'package:flutter_iconly/flutter_iconly.dart';
import 'package:myactivity_project/models/Approval%20Return/models_approval_return_list.dart';
import 'package:myactivity_project/models/ID%20CASH/model_idacash_cust.dart';
import 'package:myactivity_project/models/ID%20CASH/model_idcash.dart';
import 'package:myactivity_project/models/ID%20CASH/model_idcash_bulan.dart';
import 'package:myactivity_project/models/ID%20CASH/model_idcash_hari.dart';
import 'package:myactivity_project/models/ID%20CASH/model_idcash_tahun.dart';
import 'package:myactivity_project/service/API_service/API_service.dart';
import 'package:myactivity_project/tools/keyboard.dart';
import 'package:myactivity_project/models/model_log.dart';
import 'package:myactivity_project/tools/device_info.dart';
import 'package:myactivity_project/utils/format_number.dart';
import 'package:myactivity_project/widget/import.dart';
import 'package:myactivity_project/service/SP_service/SP_service.dart';
import 'package:pin_code_fields/pin_code_fields.dart';
import 'package:pin_code_fields/pin_code_fields.dart';
import 'package:pretty_qr_code/pretty_qr_code.dart';
import 'package:screen_brightness/screen_brightness.dart';
import 'package:myactivity_project/tools/settingsralstools.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:syncfusion_flutter_barcodes/barcodes.dart';

import '../../cubit/id_cash/id_cash_cubit.dart';
import '../../cubit/login/login_cubit.dart';
import '../../data/model/data_member_card_body.dart';
import '../../data/model/data_member_card_response.dart' as memberResponse;
import '../../data/model/data_member_card_response.dart';
import '../../data/model/login_body.dart';
import '../../utils/dismiss_keyboard.dart';

part 'ramayana_idcash.dart';
part 'ramayana_id_cash_riwayat.dart';
part 'ramayana_idcash_pin.dart';
part 'ramayana_idcash_riawayatTahun.dart';
part 'ramayana_idcash_riwayatBulan.dart';
part 'ramayana_idcashbarcode.dart';
part 'ramayana_idcash_pin2.dart';
