import 'dart:collection';
import 'dart:convert';
import 'dart:developer';
import 'dart:io';
import 'dart:math';
import 'package:device_info_plus/device_info_plus.dart';
import 'package:dio/dio.dart';
import 'package:expandable_bottom_bar/expandable_bottom_bar.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:flutter_udid/flutter_udid.dart';
import 'package:form_field_validator/form_field_validator.dart';
import 'package:myactivity_project/data/model/get_task_response.dart'
    as GetTaskResponse;
import 'package:myactivity_project/models/My%20Activity/model_edit_myactivity.dart';
import 'package:myactivity_project/models/My%20Activity/model_list_project.dart';
import 'package:myactivity_project/models/My%20Activity/model_list_task.dart';
import 'package:myactivity_project/widget/import.dart';
import 'package:file_picker/file_picker.dart';
import 'package:intl/intl.dart';
import 'package:flutter/services.dart';
import 'package:myactivity_project/service/API_service/API_service.dart';
import 'package:myactivity_project/service/SP_service/SP_service.dart';
import 'package:myactivity_project/tools/settingsralstools.dart';
import 'package:http/http.dart' as http;
import 'package:notification_permissions/notification_permissions.dart'
    as notifPermission;
import 'package:permission_handler/permission_handler.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../../cubit/myactivity/myactivity_cubit.dart';
part 'ramayana_myactivity.dart';
