// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-zacloIHqq5UUlbjJbBH0CI7xIyZFlcU',
    appId: '1:212593325478:web:f898ebd3f7bd802b21cb67',
    messagingSenderId: '212593325478',
    projectId: 'realtime-rals',
    authDomain: 'realtime-rals.firebaseapp.com',
    databaseURL: 'https://realtime-rals-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-rals.appspot.com',
    measurementId: 'G-HM1TMXYTH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQi8mPylGo53ulx8iiw99rF6ET1WvExr4',
    appId: '1:212593325478:android:1059f57ad3aa936421cb67',
    messagingSenderId: '212593325478',
    projectId: 'realtime-rals',
    databaseURL: 'https://realtime-rals-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-rals.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjEfFx5X3J3mEGRhsjthtY-WIBv50mrt0',
    appId: '1:212593325478:ios:58362fa621138ce021cb67',
    messagingSenderId: '212593325478',
    projectId: 'realtime-rals',
    databaseURL: 'https://realtime-rals-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-rals.appspot.com',
    iosBundleId: 'com.example.myactivityProjectDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjEfFx5X3J3mEGRhsjthtY-WIBv50mrt0',
    appId: '1:212593325478:ios:58362fa621138ce021cb67',
    messagingSenderId: '212593325478',
    projectId: 'realtime-rals',
    databaseURL: 'https://realtime-rals-default-rtdb.firebaseio.com',
    storageBucket: 'realtime-rals.appspot.com',
    iosBundleId: 'com.example.myactivityProjectDev',
  );
}
