import 'dart:async';
import 'dart:convert';
import 'dart:developer';

import 'package:device_info_plus/device_info_plus.dart';
import 'package:dio/dio.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_iconly/flutter_iconly.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:flutter_windowmanager/flutter_windowmanager.dart';
import 'package:form_field_validator/form_field_validator.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:http/http.dart' as http;
import 'package:in_app_update/in_app_update.dart';
import 'package:intl/intl.dart';
import 'package:motion_toast/motion_toast.dart';
import 'package:myactivity_project/base/base_params.dart' as baseParam;
import 'package:myactivity_project/base/base_paths.dart' as basePath;
import 'package:myactivity_project/database/db_log_login_offline.dart';
import 'package:myactivity_project/models/Login%20Offline/model_log_login_offline.dart';
import 'package:myactivity_project/service/SP_service/SP_service.dart';
import 'package:myactivity_project/tools/settingsralstools.dart';
import 'package:myactivity_project/widget/VOID/import.dart';
import 'package:myactivity_project/widget/import.dart';
import 'package:native_id/native_id.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:rflutter_alert/rflutter_alert.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:sim_data_plus/sim_data.dart';

import '../../base/base_params.dart';
import '../../cubit/login/login_cubit.dart';
import '../../data/model/create_my_log_body.dart';
import '../../data/model/login_body.dart';
import '../../utils/app_shared_pref.dart';
import '../../utils/get_file.dart';
import '../../utils/keyboard_utils.dart';
import '../../utils/popup_widget.dart';
import '../../utils/random_number.dart';

part 'ramayana_login_new.dart';
part 'ramayana_login_offline.dart';
part 'ramayana_reset.dart';
