import 'package:device_info_plus/device_info_plus.dart';
import 'package:expandable_bottom_bar/expandable_bottom_bar.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/services.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:flutter_udid/flutter_udid.dart';
import 'package:google_fonts/google_fonts.dart';
import 'dart:convert';
import 'package:intl/intl.dart';
import 'package:flutter/material.dart';
import 'package:flutter_iconly/flutter_iconly.dart';
import 'package:launch_review/launch_review.dart';
import 'package:motion_toast/resources/arrays.dart';
import 'package:myactivity_project/models/ID%20CASH/model_idacash_cust.dart';
import 'package:myactivity_project/tools/device_info.dart';
import 'package:dio/dio.dart';
import 'package:myactivity_project/service/SP_service/SP_service.dart';
import 'package:myactivity_project/service/API_service/API_service.dart';
import 'dart:io';
import 'dart:async';
import 'package:http/http.dart' as http;
import 'package:myactivity_project/widget/import.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:rflutter_alert/rflutter_alert.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:form_field_validator/form_field_validator.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:motion_toast/motion_toast.dart';
import 'package:myactivity_project/tools/settingsralstools.dart';
import 'package:in_app_update/in_app_update.dart';


part 'ramayana_login_new.dart';
part 'ramayana_reset.dart';